<?php
return array (
  26 => 
  array (
    'posid' => '26',
    'modelid' => '16',
    'catid' => '0',
    'name' => '绘画设计学员',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '1',
    'thumb' => '',
  ),
  32 => 
  array (
    'posid' => '32',
    'modelid' => '13',
    'catid' => '0',
    'name' => '摄影活动视频',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '1',
    'thumb' => '',
  ),
  33 => 
  array (
    'posid' => '33',
    'modelid' => '13',
    'catid' => '0',
    'name' => '影视课程视频',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '1',
    'thumb' => '',
  ),
  34 => 
  array (
    'posid' => '34',
    'modelid' => '13',
    'catid' => '0',
    'name' => '影视活动视频',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '1',
    'thumb' => '',
  ),
  35 => 
  array (
    'posid' => '35',
    'modelid' => '13',
    'catid' => '0',
    'name' => '美术课程视频',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '1',
    'thumb' => '',
  ),
  36 => 
  array (
    'posid' => '36',
    'modelid' => '13',
    'catid' => '0',
    'name' => '美术活动视频',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '1',
    'thumb' => '',
  ),
  37 => 
  array (
    'posid' => '37',
    'modelid' => '15',
    'catid' => '0',
    'name' => '班级活动',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '1',
    'thumb' => '',
  ),
  38 => 
  array (
    'posid' => '38',
    'modelid' => '15',
    'catid' => '0',
    'name' => '技术交流',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '1',
    'thumb' => '',
  ),
  39 => 
  array (
    'posid' => '39',
    'modelid' => '15',
    'catid' => '0',
    'name' => '媒体报道',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '1',
    'thumb' => '',
  ),
  40 => 
  array (
    'posid' => '40',
    'modelid' => '15',
    'catid' => '0',
    'name' => '教师寄语',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '1',
    'thumb' => '',
  ),
  41 => 
  array (
    'posid' => '41',
    'modelid' => '15',
    'catid' => '0',
    'name' => '影视资讯',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '1',
    'thumb' => '',
  ),
  42 => 
  array (
    'posid' => '42',
    'modelid' => '15',
    'catid' => '0',
    'name' => '摄影资讯',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '1',
    'thumb' => '',
  ),
  31 => 
  array (
    'posid' => '31',
    'modelid' => '13',
    'catid' => '0',
    'name' => '摄影课程视频',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '1',
    'thumb' => '',
  ),
  30 => 
  array (
    'posid' => '30',
    'modelid' => '16',
    'catid' => '0',
    'name' => '美术作品',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '1',
    'thumb' => '',
  ),
  25 => 
  array (
    'posid' => '25',
    'modelid' => '16',
    'catid' => '0',
    'name' => '摄影摄像学员',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '1',
    'thumb' => '',
  ),
  18 => 
  array (
    'posid' => '18',
    'modelid' => '12',
    'catid' => '0',
    'name' => '影视表演老师',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '1',
    'thumb' => '',
  ),
  19 => 
  array (
    'posid' => '19',
    'modelid' => '12',
    'catid' => '0',
    'name' => '摄影摄像老师',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '1',
    'thumb' => '',
  ),
  20 => 
  array (
    'posid' => '20',
    'modelid' => '12',
    'catid' => '0',
    'name' => '绘画设计老师',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '1',
    'thumb' => '',
  ),
  21 => 
  array (
    'posid' => '21',
    'modelid' => '18',
    'catid' => '0',
    'name' => '科学影视表演',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '1',
    'thumb' => '',
  ),
  22 => 
  array (
    'posid' => '22',
    'modelid' => '18',
    'catid' => '0',
    'name' => '科学摄影摄像',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '1',
    'thumb' => '',
  ),
  23 => 
  array (
    'posid' => '23',
    'modelid' => '18',
    'catid' => '0',
    'name' => '科学绘画设计',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '1',
    'thumb' => '',
  ),
  24 => 
  array (
    'posid' => '24',
    'modelid' => '16',
    'catid' => '0',
    'name' => '影视表演学员',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '1',
    'thumb' => '',
  ),
  27 => 
  array (
    'posid' => '27',
    'modelid' => '16',
    'catid' => '0',
    'name' => '电影作品',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '1',
    'thumb' => '',
  ),
  28 => 
  array (
    'posid' => '28',
    'modelid' => '16',
    'catid' => '0',
    'name' => '电视作品',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '1',
    'thumb' => '',
  ),
  29 => 
  array (
    'posid' => '29',
    'modelid' => '16',
    'catid' => '0',
    'name' => '摄影作品',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '1',
    'thumb' => '',
  ),
  43 => 
  array (
    'posid' => '43',
    'modelid' => '15',
    'catid' => '0',
    'name' => '美术资讯',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '1',
    'thumb' => '',
  ),
);
?>